// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"

	"gorm.io/plugin/soft_delete"
)

const TableNameTodo = "todo"

type Todo struct {
	ID         int64                 `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id"`
	Title      string                `gorm:"column:title;not null;comment:标题" json:"title"`
	Status     bool                  `gorm:"column:status;not null;comment:状态(是否完成)" json:"status"`
	CreateTime time.Time             `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"`
	UpdateTime time.Time             `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"`
	IsDelete   soft_delete.DeletedAt `gorm:"column:is_delete;not null;comment:是否删除;softDelete:flag" json:"is_delete"`
}

func (*Todo) TableName() string {
	return TableNameTodo
}
